# Generated by Django 2.2.8 on 2020-01-18 18:33

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('hood', '0002_blogpost_date_posted'),
    ]

    operations = [
        migrations.AddField(
            model_name='business',
            name='date_posted',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
