# Generated by Django 2.2.8 on 2020-01-18 19:26

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('hood', '0003_business_date_posted'),
    ]

    operations = [
        migrations.AddField(
            model_name='authorities',
            name='date_posted',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
